import firebase from 'firebase/app';

function list() {
  firebase.firestore().collection('wine').get()
    .then((d) => d.docs.map((doc) => doc.data()));
}

function listColors() {
  return [
    'Red',
    'White',
    'Rose',
    'Sparkling',
  ];
}

function listRegions() {
  return [
    'France',
    'Italy',
    'Spain',
    'United States',
    'Argentina',
    'Australia',
    'Germany',
    'South Africa',
    'Chile',
    'Portugal',
    'China',
    'Other',
  ];
}

function listFlavors() {
  return [
    'Quince',
    'Apple',
    'Pear',
    'Nectarine',
    'Peach',
    'Apricot',
    'Persimmon',
    'Iris',
    'Peony',
    'Elderflower',
    'Lilac',
    'Jasmine',
    'Honeysuckle',
    'Violet',
    'Lavender',
    'Rose',
    'Potpourri',
    'Hibiscus',
    'Citrus',
    'Lime',
    'Lemon',
    'Grapefruit',
    'Orange',
    'Pineapple',
    'Mango',
    'Guava',
    'Passion Fruit',
    'Lychee',
    'Bubblegum',
    'Cranberry',
    'Red Plum',
    'Pomegranate',
    'Sour Cherry',
    'Strawberry',
    'Cherry',
    'Raspberry',
    'Boysenberry',
    'Black Currant',
    'Black Cherry',
    'Plum',
    'Blackberry',
    'Blueberry',
    'Olive',
    'Raisin',
    'Fig',
    'Date',
    'Fruitcake',
    'Beeswax',
    'Ginger',
    'Honey',
    'White Pepper',
    'Red Pepper',
    'Black Pepper',
    'Cinnamon',
    'Anise',
    '5-Spice',
    'Fennel',
    'Eucalyptus',
    'Mint',
    'Thyme',
    'Grass',
    'Tomato Leaf',
    'Gooseberry',
    'Bell Pepper',
    'Jalapeño',
    'Bitter Almond',
    'Tomato',
    'Black Tea',
    'Clay Pot',
    'Slate',
    'Wet Gravel',
    'Potting Soil',
    'Red Beet',
    'Volcanic Rocks',
    'Petroleum',
    'Butter',
    'Cream',
    'Sourdough',
    'Lager',
    'Truffle',
    'Mushroom',
    'Vanilla',
    'Coconut',
    'Baking Spices',
    'Cigar Box',
    'Smoke',
    'Dill',
    'Dried Fruit',
    'Nutty Flavors',
    'Tobacco',
    'Coffee',
    'Cocoa',
    'Leather',
    'Toffee',
    'Vinegar',
    'Cured Meat',
    'Boiled Eggs',
    'Burnt Rubber',
    'Lit Match',
    'Garlic',
    'Onion',
    'Cat Pee',
  ];
}

export default {
  list,
  listColors,
  listRegions,
  listFlavors,
};
